use_default_settings: true
server:
  secret_key: "6100db7baa7876058ad8f3ae3b54111a53902c9c9e3d4d824edadc669efb7b9f"
  bind_address: "0.0.0.0"
  image_proxy: true
  limiter: false
search:
  formats:
    - html
    - json
